module.exports = function getCategory() {
  return {
    bookmarkKey: 'bookmark',
    mediaFileKey: 'mediaFile',
    categoryObject: {
      id: 'lrn:segment1:segment2:segment3:segment4:segment5:segment6',
      key: 'bookmarks',
      pluginOwner: 'leebrary',
      creatable: 1,
      createUrl: null,
      duplicable: 1,
      provider: 'leebrary',
      componentOwner: 'leebrary',
      listCardComponent: null,
      listItemComponent: null,
      detailComponent: null,
      canUse: '*',
      order: 2,
      deleted: 0,
    },
    categoryId: 'lrn:segment1:segment2:segment3:segment4:segment5:segment6',
    mediaFileCategoryObject: {
      id: 'lrn:segment1:segment2:segment3:segment4:segment5:tnemges6',
      key: 'media-files',
      pluginOwner: 'leebrary',
      creatable: 1,
      createUrl: null,
      duplicable: 1,
      provider: 'leebrary',
      componentOwner: 'leebrary',
      listCardComponent: null,
      listItemComponent: null,
      detailComponent: null,
      canUse: '*',
      order: 1,
      deleted: 0,
    },
  };
};
