/* eslint-disable sonarjs/no-duplicate-string */
module.exports = function getMenuItems() {
  return {
    menuItems: [
      {
        id: '06fb613c-d222-404b-8bcf-1ebf1983e21c',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.scorm',
        parentKey: null,
        pluginName: 'leebrary',
        order: 207,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/scorm/menu-icon.svg',
        activeIconSvg: '/public/scorm/menu-icon.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: '36e90ecb-1a12-446e-8e34-cd1c9a69f38d',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.content-creator',
        parentKey: null,
        pluginName: 'leebrary',
        order: 201,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/content-creator/menu-icon-active.svg',
        activeIconSvg: '/public/content-creator/menu-icon-active.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'b4dace05-d988-4439-a766-45517731000c',
        menuKey: 'leebrary.categories',
        key: 'leebrary.media-files',
        parentKey: null,
        pluginName: 'leebrary',
        order: 1,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/leebrary/media-files.svg',
        activeIconSvg: '/public/leebrary/media-files.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'b68466d4-3926-45eb-b93a-6f90876f2342',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.feedback',
        parentKey: null,
        pluginName: 'leebrary',
        order: 205,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/feedback/menu-icon.svg',
        activeIconSvg: '/public/feedback/menu-icon-active.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'b7d693da-7126-4301-aa48-5b9dc8642bf8',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.tests',
        parentKey: null,
        pluginName: 'leebrary',
        order: 203,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/tests/menu-icon.svg',
        activeIconSvg: '/public/tests/menu-icon.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'ce1ea4ba-9feb-4068-90cd-f4a0d5b2941b',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.task',
        parentKey: null,
        pluginName: 'leebrary',
        order: 202,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/tasks/leebrary-menu-icon.svg',
        activeIconSvg: '/public/tasks/leebrary-menu-icon.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'd0ff862e-2d5f-4ccd-96d9-70122b304686',
        menuKey: 'leebrary.categories',
        key: 'leebrary.tests-questions-banks',
        parentKey: null,
        pluginName: 'leebrary',
        order: 204,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/leebrary-tests/menu-icon.svg',
        activeIconSvg: '/public/leebrary-tests/menu-icon.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'f4d359a0-fcf5-463f-b633-358459c72cb4',
        menuKey: 'leebrary.categories',
        key: 'leebrary.bookmarks',
        parentKey: null,
        pluginName: 'leebrary',
        order: 2,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/leebrary/bookmarks.svg',
        activeIconSvg: '/public/leebrary/bookmarks.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
      {
        id: 'ff766308-79b3-45f9-b303-462bb732adff',
        menuKey: 'leebrary.categories',
        key: 'leebrary.assignables.learningpaths.module',
        parentKey: null,
        pluginName: 'leebrary',
        order: 206,
        fixed: 0,
        iconName: null,
        activeIconName: null,
        iconSvg: '/public/learning-paths/modules-leebrary-icon.svg',
        activeIconSvg: '/public/learning-paths/modules-leebrary-icon.svg',
        iconAlt: null,
        url: null,
        window: 'SELF',
        disabled: null,
      },
    ],
  };
};
