import removeFile from './removeFile';
import uploadFiles from './uploadFiles';
import listAllMyFiles from './listAllMyFiles';
import listCategories from './listCategories';
import newAsset from './newAsset';
import getAsset from './getAsset';
import getAssets from './getAssets';
import getAssetsByIds from './getAssetsByIds';
import setPermissions from './setPermissions';
import getUrlMetadata from './getUrlMetadata';

export const removeFileRequest = removeFile;
export const uploadFilesRequest = uploadFiles;
export const listAllMyFilesRequest = listAllMyFiles;
export const listCategoriesRequest = listCategories;
export const newAssetRequest = newAsset;
export const getAssetRequest = getAsset;
export const getAssetsRequest = getAssets;
export const getAssetsByIdsRequest = getAssetsByIds;
export const setPermissionsRequest = setPermissions;
export const getUrlMetadataRequest = getUrlMetadata;
