/**
 * Retrieves a category by its key.
 *
 * @async
 * @function getByKey
 * @param {Object} options - Input options.
 * @param {string} options.key - The key of the category to retrieve.
 * @param {string[]} [options.columns] - The optional columns to select from the category.
 * @param {import("moleculer").Context} options.ctx - The Moleculer request context.
 * @returns {Promise<Object|null>} The category object or null if not found.
 *
 * @comment Generated by GPT
 */

async function getByKey({ key, columns, ctx }) {
  const category = await ctx.tx.db.Categories.findOne({ key }).select(columns).lean();
  if (category && category.canUse) category.canUse = JSON.parse(category.canUse);
  return category;
}

module.exports = { getByKey };
