import listCalendarConfigCalendars from './listCalendarConfigCalendars';
import getCentersWithOutAssign from './getCentersWithOutAssign';
import getCalendarsToFrontend from './getCalendarsToFrontend';
import updateCalendarConfigs from './updateCalendarConfigs';
import listKanbanEventOrders from './listKanbanEventOrders';
import saveKanbanEventOrders from './saveKanbanEventOrders';
import detailCalendarConfigs from './detailCalendarConfigs';
import getScheduleToFrontend from './getScheduleToFrontend';
import removeCalendarConfig from './removeCalendarConfig';
import listCalendarConfigs from './listCalendarConfigs';
import updateEventSubTasks from './updateEventSubTasks';
import listKanbanColumns from './listKanbanColumns';
import addCalendarConfig from './addCalendarConfig';
import updateConfigEvent from './updateConfigEvent';
import removeConfigEvent from './removeConfigEvent';
import addConfigEvent from './addConfigEvent';
import getEventTypes from './getEventTypes';
import removeEvent from './removeEvent';
import updateEvent from './updateEvent';
import addEvent from './addEvent';

export const listCalendarConfigCalendarsRequest = listCalendarConfigCalendars;
export const getCentersWithOutAssignRequest = getCentersWithOutAssign;
export const getCalendarsToFrontendRequest = getCalendarsToFrontend;
export const updateCalendarConfigsRequest = updateCalendarConfigs;
export const listKanbanEventOrdersRequest = listKanbanEventOrders;
export const saveKanbanEventOrdersRequest = saveKanbanEventOrders;
export const detailCalendarConfigsRequest = detailCalendarConfigs;
export const getScheduleToFrontendRequest = getScheduleToFrontend;
export const removeCalendarConfigRequest = removeCalendarConfig;
export const listCalendarConfigsRequest = listCalendarConfigs;
export const updateEventSubTasksRequest = updateEventSubTasks;
export const listKanbanColumnsRequest = listKanbanColumns;
export const addCalendarConfigRequest = addCalendarConfig;
export const updateConfigEventRequest = updateConfigEvent;
export const removeConfigEventRequest = removeConfigEvent;
export const addConfigEventRequest = addConfigEvent;
export const getEventTypesRequest = getEventTypes;
export const removeEventRequest = removeEvent;
export const updateEventRequest = updateEvent;
export const addEventRequest = addEvent;
