const platform = require('../src/services/platform');

module.exports = {
  query: platform.query,
  setName: platform.setName,
  getName: platform.getName,
  setEmail: platform.setEmail,
  getEmail: platform.getEmail,
  addLocale: platform.addLocale,
  getLocales: platform.getLocales,
  setHostname: platform.setHostname,
  getHostname: platform.getHostname,
  getContactName: platform.getContactName,
  setContactName: platform.setContactName,
  setContactPhone: platform.setContactPhone,
  setContactEmail: platform.setContactEmail,
  getContactPhone: platform.getContactPhone,
  getContactEmail: platform.getContactEmail,
  setDefaultLocale: platform.setDefaultLocale,
  getDefaultLocale: platform.getDefaultLocale,
  setAppearanceLogo: platform.setAppearanceLogo,
  getAppearanceLogo: platform.getAppearanceLogo,
  setAppearanceMainColor: platform.setAppearanceMainColor,
  getAppearanceMainColor: platform.getAppearanceMainColor,
};
