import login from './login';
import reset from './reset';
import addRole from './addRole';
import getRole from './getRole';
import recover from './recover';
import canReset from './canReset';
import listRoles from './listRoles';
import listUsers from './listUsers';
import todayQuote from './todayQuote';
import updateRole from './updateRole';
import addProfile from './addProfile';
import getProfile from './getProfile';
import listCenters from './listCenters';
import listActions from './listActions';
import getContacts from './getContacts';
import listProfiles from './listProfiles';
import updateProfile from './updateProfile';
import listPermissions from './listPermissions';
import getUserProfiles from './getUserProfiles';
import getRememberProfile from './getRememberProfile';
import setRememberProfile from './setRememberProfile';
import getPlatformLocales from './getPlatformLocales';
import getUserProfileToken from './getUserProfileToken';
import getDefaultPlatformLocale from './getDefaultPlatformLocale';
import getPermissionsWithActionsIfIHave from './getPermissionsWithActionsIfIHave';

export const loginRequest = login;
export const resetRequest = reset;
export const addRoleRequest = addRole;
export const getRoleRequest = getRole;
export const recoverRequest = recover;
export const canResetRequest = canReset;
export const listRolesRequest = listRoles;
export const listUsersRequest = listUsers;
export const updateRoleRequest = updateRole;
export const addProfileRequest = addProfile;
export const getProfileRequest = getProfile;
export const todayQuoteRequest = todayQuote;
export const listCentersRequest = listCenters;
export const listActionsRequest = listActions;
export const getContactsRequest = getContacts;
export const listProfilesRequest = listProfiles;
export const updateProfileRequest = updateProfile;
export const listPermissionsRequest = listPermissions;
export const getUserProfilesRequest = getUserProfiles;
export const getRememberProfileRequest = getRememberProfile;
export const setRememberProfileRequest = setRememberProfile;
export const getPlatformLocalesRequest = getPlatformLocales;
export const getUserProfileTokenRequest = getUserProfileToken;
export const getDefaultPlatformLocaleRequest = getDefaultPlatformLocale;
export const getPermissionsWithActionsIfIHaveRequest = getPermissionsWithActionsIfIHave;
