import activateUser from './activateUser';
import addProfile from './addProfile';
import addRole from './addRole';
import addUsersBulk from './addUsersBulk';
import canRegisterPassword from './canRegisterPassword';
import canReset from './canReset';
import getContacts from './getContacts';
import getDataForUserAgentDatasets from './getDataForUserAgentDatasets';
import getDataForUserDatasets from './getDataForUserDatasets';
import getDefaultPlatformLocale from './getDefaultPlatformLocale';
import getPermissionsWithActionsIfIHave from './getPermissionsWithActionsIfIHave';
import getPlatformLocales from './getPlatformLocales';
import getPlatformTheme from './getPlatformTheme';
import getProfile from './getProfile';
import getProfileSysName from './getProfileSysName';
import getRememberLogin from './getRememberLogin';
import getRole from './getRole';
import getSystemDataFieldsConfig from './getSystemDataFieldsConfig';
import getUserAgentDetailForPage from './getUserAgentDetailForPage';
import getUserAgentsInfo from './getUserAgentsInfo';
import getUserCenterProfileToken from './getUserCenterProfileToken';
import getUserCenters from './getUserCenters';
import getUserDetailForPage from './getUserDetailForPage';
import getUserProfileToken from './getUserProfileToken';
import getUserProfiles from './getUserProfiles';
import listActions from './listActions';
import listCenters from './listCenters';
import listPermissions from './listPermissions';
import listProfiles from './listProfiles';
import listRoles from './listRoles';
import listUsers from './listUsers';
import login from './login';
import recover from './recover';
import registerPassword from './registerPassword';
import removeRememberLogin from './removeRememberLogin';
import reset from './reset';
import saveDataForUserAgentDatasets from './saveDataForUserAgentDatasets';
import saveDataForUserDatasets from './saveDataForUserDatasets';
import saveSystemDataFieldsConfig from './saveSystemDataFieldsConfig';
import searchUserAgents from './searchUserAgents';
import sendWelcomeEmailToUser from './sendWelcomeEmailToUser';
import setRememberLogin from './setRememberLogin';
import todayQuote from './todayQuote';
import updateProfile from './updateProfile';
import updateRole from './updateRole';
import updateUser from './updateUser';
import updateUserAgent from './updateUserAgent';
import updateUserImage from './updateUserImage';

import addCenter from '@users/request/addCenter';
import removeCenter from '@users/request/removeCenter';
import updateSessionConfig from '@users/request/updateSessionConfig';

export const loginRequest = login;
export const resetRequest = reset;
export const addRoleRequest = addRole;
export const getRoleRequest = getRole;
export const recoverRequest = recover;
export const canResetRequest = canReset;
export const listRolesRequest = listRoles;
export const listUsersRequest = listUsers;
export const addCenterRequest = addCenter;
export const updateUserRequest = updateUser;
export const updateRoleRequest = updateRole;
export const addProfileRequest = addProfile;
export const getProfileRequest = getProfile;
export const todayQuoteRequest = todayQuote;
export const listCentersRequest = listCenters;
export const listActionsRequest = listActions;
export const getContactsRequest = getContacts;
export const activateUserRequest = activateUser;
export const removeCenterRequest = removeCenter;
export const addUsersBulkRequest = addUsersBulk;
export const listProfilesRequest = listProfiles;
export const updateProfileRequest = updateProfile;
export const getUserCentersRequest = getUserCenters;
export const getPlatformThemeRequest = getPlatformTheme;
export const getProfileSysNameRequest = getProfileSysName;
export const updateSessionConfigRequest = updateSessionConfig;
export const listPermissionsRequest = listPermissions;
export const getUserProfilesRequest = getUserProfiles;
export const updateUserAgentRequest = updateUserAgent;
export const searchUserAgentsRequest = searchUserAgents;
export const registerPasswordRequest = registerPassword;
export const getUserAgentsInfoRequest = getUserAgentsInfo;
export const getRememberLoginRequest = getRememberLogin;
export const updateUserImageRequest = updateUserImage;
export const setRememberLoginRequest = setRememberLogin;
export const getPlatformLocalesRequest = getPlatformLocales;
export const removeRememberLoginRequest = removeRememberLogin;
export const canRegisterPasswordRequest = canRegisterPassword;
export const getUserProfileTokenRequest = getUserProfileToken;
export const getUserDetailForPageRequest = getUserDetailForPage;
export const getDataForUserDatasetsRequest = getDataForUserDatasets;
export const sendWelcomeEmailToUserRequest = sendWelcomeEmailToUser;
export const saveDataForUserDatasetsRequest = saveDataForUserDatasets;
export const getDefaultPlatformLocaleRequest = getDefaultPlatformLocale;
export const getSystemDataFieldsConfigRequest = getSystemDataFieldsConfig;
export const getUserCenterProfileTokenRequest = getUserCenterProfileToken;
export const getUserAgentDetailForPageRequest = getUserAgentDetailForPage;
export const saveSystemDataFieldsConfigRequest = saveSystemDataFieldsConfig;
export const getDataForUserAgentDatasetsRequest = getDataForUserAgentDatasets;
export const saveDataForUserAgentDatasetsRequest = saveDataForUserAgentDatasets;
export const getPermissionsWithActionsIfIHaveRequest = getPermissionsWithActionsIfIHave;
