const platform = require('../src/services/platform');

module.exports = {
  query: platform.query,
  setName: platform.setName,
  getName: platform.getName,
  setEmail: platform.setEmail,
  getEmail: platform.getEmail,
  addLocale: platform.addLocale,
  getLocales: platform.getLocales,
  setHostname: platform.setHostname,
  getHostname: platform.getHostname,
  setHostnameApi: platform.setHostnameApi,
  getHostnameApi: platform.getHostnameApi,
  setEmailLogo: platform.setEmailLogo,
  getEmailLogo: platform.getEmailLogo,
  setSquareLogo: platform.setSquareLogo,
  getSquareLogo: platform.getSquareLogo,
  getContactName: platform.getContactName,
  setContactName: platform.setContactName,
  setContactPhone: platform.setContactPhone,
  setContactEmail: platform.setContactEmail,
  getContactPhone: platform.getContactPhone,
  getContactEmail: platform.getContactEmail,
  setDefaultLocale: platform.setDefaultLocale,
  getDefaultLocale: platform.getDefaultLocale,
  setLandscapeLogo: platform.setLandscapeLogo,
  getLandscapeLogo: platform.getLandscapeLogo,
  getEmailWidthLogo: platform.getEmailWidthLogo,
  setEmailWidthLogo: platform.setEmailWidthLogo,
  setAppearanceDarkMode: platform.setAppearanceDarkMode,
  getAppearanceDarkMode: platform.getAppearanceDarkMode,
  setAppearanceMainColor: platform.setAppearanceMainColor,
  getAppearanceMainColor: platform.getAppearanceMainColor,
  setAppearanceMenuMainColor: platform.setAppearanceMenuMainColor,
  getAppearanceMenuMainColor: platform.getAppearanceMenuMainColor,
  setAppearanceMenuDrawerColor: platform.setAppearanceMenuDrawerColor,
  getAppearanceMenuDrawerColor: platform.getAppearanceMenuDrawerColor,
  getPicturesEmptyStates: platform.getPicturesEmptyStates,
  setPicturesEmptyStates: platform.setPicturesEmptyStates,
};
